### ISSUE TITLE
Extension does not activate without manually setting Dark Theme to true in settings

### ISSUE THREAD

**Issue by elijahYCWu** [ThomasFKJorna/zotero-night#58] opened 2022-08-13 01:39 UTC
When I updated Zotero to 6.0.11 yesterday, the plugin just couldn't work anymore.

**Comment by tefkah** [comment] 2022-08-13 16:20
Could you provide some more details about "just couldn't work" means in this case? 

And could you provide some info about your OS etc?

**Comment by mscott99** [comment] 2022-08-14 04:46
Same here, but I am on the 6.0.12-beta version. For me,  I installed the add-on, and nothing happened upon restart; still white.

**Comment by michaelweinold** [comment] 2022-08-15 05:59
Can confirm: not working with Zotero 6.0.11 on macOS 12.5 (21G72):
<img width="1109" alt="Screenshot 2022-08-15 at 07 58 39" src="https://user-images.githubusercontent.com/23102087/184583962-430bee79-8ea5-44c1-aaf3-2383b47de7de.png">

**Comment by tefkah** [comment] 2022-08-15 13:12
hmmm strange, ill have a look

**Comment by tefkah** [comment] 2022-08-15 13:20
Hmmmmmmmm I can't reproduce this unfortunately. Could you maybe open the Night for Zotero settings from "Tools" and try toggling the "Dark theme enabled" a couple times? Someone had success with a similar issue doing that

**Comment by tefkah** [comment] 2022-08-15 13:20
Also are y'all on Intel or M1 macs. I'm on M1 MacOS 12.5 Zotero 6.0.11 (& beta) and works fine here.

**Comment by michaelweinold** [comment] 2022-08-15 13:47
Exactly the same behaviour as described by @elijahYCWu:
> It seems that the "Dark theme enabled" switch is turned off by default, and when I turn it on, dark mode is displayed normally. But when I turn off zotero and turn it back on, the switch goes back to off and the interface shows white again. Also, no matter how I set, the dark mode is not displayed properly in the pdf editing page.

I'm using Zotero on ARM64 (M1).

**Comment by mscott99** [comment] 2022-08-15 20:03
I am also on an M1 mac mini. I will try that solution.

**Comment by zhiyuanzhai** [comment] 2022-09-19 03:28
I have a short demo on this problem here.
https://user-images.githubusercontent.com/37478391/190945249-8db20b94-c0a4-46ca-8f7e-8c3613f87166.mp4

**Comment by HeDylan** [comment] 2022-10-10 19:24
same problem here, and nothing changed about the pdf background color

**Comment by Udneowi** [comment] 2022-10-12 18:26
A temporary fix is found in #53.

> Upon further review, I got it to work.
> 
> Here was my fumbling around:
> 
> After installation, restarted Zotero Under Tools|Night Preferences, clicked on "Enabled Dark Theme." A check only appears in the checkbox when clicking twice, but the Dark Theme turned on for Zotero in the background while the Night Preferences drop down menu was still open. Clicked on the "Dark" radio button. Closed the Night Preferences menu. In the vvveeerrryyy right hand corner of Zotero, an icon appears.
> 
> <img alt="image" width="52" src="https://user-images.githubusercontent.com/3004126/182252864-c3c36f3b-3116-4238-a139-07bcb70fdb4d.png">
> 
> Toggling that icon now turns on the dark mode both for Zotero AND in the pdf reader.
> 
> Thus I got the plug in to work as advertised, just with a few more clicks than was obvious.
> 
> Thanks again for creating this.

Worked for me. Intel MacOS 13 Beta 9.

**Comment by tefkah** [comment] 2022-11-04 15:42
this is maybe fixed in the latest release!

**Closed as completed** 2022-11-05 12:16 UTC

**Comment by JamesNolan17** [comment] 2023-04-07 14:07
<img width="1264" alt="22 06 57#04-07" src="https://user-images.githubusercontent.com/61568403/230622450-f7c0594e-cc14-4712-a2c6-749a6ab7e5bb.png">
Now on macOS there is still no icon that 'turns on the dark mode both for Zotero AND in the pdf reader.'
